# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20151127_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbBankStatement',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('trans_date', models.DateField(verbose_name='\u4ea4\u6613\u65e5\u671f', editable=False)),
                ('trans_time', models.TimeField(verbose_name='\u4ea4\u6613\u65f6\u95f4', null=True, editable=False, blank=True)),
                ('bank_account', models.CharField(default=b'', max_length=30)),
                ('source_side', models.CharField(blank=True, max_length=6, null=True, choices=[(b'B', '\u94f6\u884c'), (b'I', '\u5e02\u573a')])),
                ('trans_code', models.CharField(max_length=20)),
                ('serial_no', models.CharField(max_length=60, db_index=True)),
                ('inst_serial', models.CharField(default=b'', unique=True, max_length=60, blank=True)),
                ('amount', models.DecimalField(max_digits=30, decimal_places=5)),
                ('client_no', models.CharField(max_length=20)),
                ('inst_no', models.CharField(max_length=30)),
                ('busi_type', models.CharField(default=b'6', max_length=6, choices=[(b'6', '\u4fdd\u8bc1\u91d1'), (b'7', '\u8d37\u6b3e')])),
                ('money_kind', models.CharField(default=b'01', max_length=6)),
                ('inst_func_acc', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('charge', models.DecimalField(max_digits=30, decimal_places=5)),
                ('reserve1', models.CharField(default=b'', max_length=300)),
                ('reserve2', models.CharField(default=b'', max_length=300)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='AbRechargeWithdrawErrorStatus',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('status', models.IntegerField(choices=[(1, '\u94f6\u884c\u6210\u529f\u5e02\u573a\u5931\u8d25'), (2, '\u94f6\u884c\u5931\u8d25\u5e02\u573a\u6210\u529f'), (3, '\u94f6\u884c\u5e02\u573a\u91d1\u989d\u4e0d\u5339\u914d')])),
                ('result', models.IntegerField(default=1, choices=[(1, '\u672a\u5904\u7406'), (2, '\u5904\u7406\u4e2d'), (3, '\u5df2\u4fee\u6b63')])),
                ('fixed_user', models.CharField(default=b'', max_length=20)),
                ('fixed_event', models.CharField(default=b'', max_length=20)),
                ('fixed_comment', models.CharField(default=b'', max_length=500)),
                ('fixed_time', models.DateTimeField(verbose_name='\u4fee\u6b63\u65f6\u95f4', null=True, editable=False, blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, blank=True, to='finance.AbBankStatement', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliPaymentBill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('trans_date', models.DateTimeField()),
                ('transaction_id', models.CharField(default=b'', max_length=70, db_index=True)),
                ('merchant_out_order_no', models.CharField(default=b'', max_length=70, db_index=True)),
                ('trans_out_order_no', models.CharField(default=b'', max_length=70, db_index=True)),
                ('total_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True)),
                ('trade_refund_amount', models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True)),
                ('balance', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('income', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('outcome', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('partner_id', models.CharField(default=b'', max_length=40)),
                ('sub_trans_code_msg', models.CharField(default=b'', max_length=30)),
                ('trans_code_msg', models.CharField(default=b'', max_length=100, blank=True)),
                ('bank_name', models.CharField(default=b'', max_length=50)),
                ('bank_account_no', models.CharField(default=b'', max_length=40)),
                ('bank_account_name', models.CharField(default=b'', max_length=40)),
                ('memo', models.CharField(default=b'', max_length=200)),
                ('buyer_account', models.CharField(default=b'', max_length=60)),
                ('seller_account', models.CharField(default=b'', max_length=60)),
                ('seller_fullname', models.CharField(default=b'', max_length=60)),
                ('currency', models.CharField(default=b'', max_length=10)),
                ('deposit_bank_no', models.CharField(default=b'', max_length=100)),
                ('goods_title', models.CharField(default=b'', max_length=200)),
                ('iw_account_log_id', models.CharField(default=b'', max_length=100)),
                ('trans_account', models.CharField(default=b'', max_length=100)),
                ('other_account_email', models.CharField(default=b'', max_length=100)),
                ('other_account_fullname', models.CharField(default=b'', max_length=100)),
                ('other_user_id', models.CharField(default=b'', max_length=100)),
                ('service_fee', models.CharField(default=b'', max_length=100)),
                ('service_fee_ratio', models.CharField(default=b'', max_length=20)),
                ('sign_product_name', models.CharField(default=b'', max_length=128)),
                ('rate', models.CharField(default=b'', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliPaymentTradeOrder',
            fields=[
                ('out_trade_no', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('uid', models.IntegerField()),
                ('order_no', models.CharField(max_length=100)),
                ('payment_type', models.CharField(default=b'1', max_length=4)),
                ('pay_service_type', models.CharField(max_length=20, choices=[(b'direct_pay', '\u5373\u65f6\u5230\u8d26'), (b'bank_pay', '\u7f51\u94f6\u652f\u4ed8')])),
                ('seller_id', models.CharField(max_length=16)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_account_name', models.CharField(max_length=100)),
                ('subject', models.CharField(default=b'', max_length=40, blank=True)),
                ('body', models.CharField(default=b'', max_length=300, blank=True)),
                ('extra_common_param', models.CharField(default=b'', max_length=100, blank=True)),
                ('extend_param', models.CharField(default=b'', max_length=100, blank=True)),
                ('it_b_pay', models.CharField(default=b'', max_length=10, blank=True)),
                ('total_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('notify_id', models.CharField(default=b'', max_length=100, blank=True)),
                ('notify_time', models.CharField(default=b'', max_length=30, blank=True)),
                ('notify_type', models.CharField(default=b'', max_length=30, blank=True)),
                ('gmt_create', models.DateTimeField(null=True, blank=True)),
                ('gmt_payment', models.DateTimeField(null=True, blank=True)),
                ('gmt_close', models.DateTimeField(null=True, blank=True)),
                ('gmt_last_modified_time', models.DateTimeField(null=True, blank=True)),
                ('time_out', models.DateTimeField(null=True, blank=True)),
                ('time_out_type', models.CharField(default=b'', max_length=30, blank=True)),
                ('bank_seq_no', models.CharField(default=b'', max_length=70, blank=True)),
                ('refund_status', models.CharField(default=b'', max_length=30, blank=True)),
                ('gmt_refund', models.DateTimeField(null=True, blank=True)),
                ('refund_total_fee', models.IntegerField(default=0)),
                ('buyer_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('buyer_email', models.CharField(default=b'', max_length=100, blank=True)),
                ('agent_user_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('transaction_id', models.CharField(default=b'', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('ali_service', models.CharField(default=b'create_direct_pay_by_user', max_length=50, blank=True)),
                ('is_order_over', models.BooleanField(default=False)),
                ('order_status', models.SmallIntegerField(default=0, choices=[(0, '\u8fdb\u884c\u4e2d'), (1, '\u652f\u4ed8\u5931\u8d25'), (2, '\u9884\u652f\u4ed8\u4e2d'), (3, '\u4ea4\u6613\u6210\u529f\uff0c\u4e14\u53ef\u5bf9\u8be5\u4ea4\u6613\u505a\u64cd\u4f5c\uff0c\u5982\uff1a\u591a\u7ea7\u5206\u6da6\u3001\u9000\u6b3e\u7b49'), (9, '\u4ea4\u6613\u6210\u529f\u4e14\u7ed3\u675f\uff0c\u4e0d\u53ef\u518d\u505a\u4efb\u4f55\u64cd\u4f5c'), (10, '\u7b49\u5f85\u5356\u5bb6\u6536\u6b3e\uff08\u4e70\u5bb6\u4ed8\u6b3e\u540e\uff0c\u5982\u679c\u5356\u5bb6\u8d26\u53f7\u88ab\u51bb\u7ed3\uff09'), (101, '\u8f6c\u5165\u9000\u6b3e'), (102, '\u9000\u6b3e\u6210\u529f'), (103, '\u9000\u6b3e\u5173\u95ed')])),
                ('ali_return_code', models.CharField(default=b'', max_length=16, null=True, blank=True)),
                ('ali_return_msg', models.CharField(default=b'', max_length=200, null=True, blank=True)),
                ('ali_result_code', models.CharField(default=b'', max_length=16, null=True, blank=True)),
                ('ali_err_code', models.CharField(default=b'', max_length=100, null=True, blank=True)),
                ('ali_err_code_des', models.CharField(default=b'', max_length=200, null=True, blank=True)),
                ('ali_trade_status', models.CharField(default=b'', max_length=100, blank=True)),
                ('ali_response', models.CharField(default=b'', max_length=1000, null=True, blank=True)),
                ('comment', models.CharField(default=b'', max_length=600)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WxPaymentBill',
            fields=[
                ('trade_no', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('wx_transaction_id', models.CharField(default=b'', max_length=100)),
                ('bill_type', models.CharField(max_length=10, choices=[(b'ALL', '\u8fd4\u56de\u5f53\u65e5\u6240\u6709\u8ba2\u5355\u4fe1\u606f\uff0c\u9ed8\u8ba4\u503c'), (b'SUCCESS', '\u8fd4\u56de\u5f53\u65e5\u6210\u529f\u652f\u4ed8\u7684\u8ba2\u5355'), (b'REFUND', '\u8fd4\u56de\u5f53\u65e5\u9000\u6b3e\u8ba2\u5355'), (b'REVOKED', '\u5df2\u64a4\u9500\u7684\u8ba2\u5355')])),
                ('trade_time', models.DateTimeField()),
                ('mch_id', models.CharField(max_length=32)),
                ('sub_mch_id', models.CharField(default=b'', max_length=32)),
                ('appid', models.CharField(max_length=32)),
                ('device_no', models.CharField(default=b'', max_length=32)),
                ('open_id', models.CharField(default=b'', max_length=128)),
                ('trade_type', models.CharField(default=b'', max_length=32)),
                ('trade_status', models.CharField(max_length=30)),
                ('bank_type', models.CharField(max_length=30)),
                ('fee_type', models.CharField(max_length=30)),
                ('total_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('coupon_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('refund_request_time', models.DateTimeField(null=True, blank=True)),
                ('refund_success_time', models.DateTimeField(null=True, blank=True)),
                ('wx_refund_no', models.CharField(default=b'', max_length=32)),
                ('mch_refund_no', models.CharField(default=b'', max_length=28)),
                ('refund_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('refund_coupon_fee', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('refund_type', models.CharField(default=b'', max_length=50)),
                ('refund_status', models.CharField(default=b'', max_length=50)),
                ('trade_name', models.CharField(default=b'', max_length=200)),
                ('trade_attach', models.CharField(default=b'', max_length=200)),
                ('service_charges', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rate', models.CharField(default=b'', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WxPaymentTradeOrder',
            fields=[
                ('trade_no', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('uid', models.IntegerField()),
                ('product_id', models.CharField(max_length=100)),
                ('device_info', models.CharField(default=b'WEB', max_length=100)),
                ('body', models.CharField(default=b'', max_length=40, blank=True)),
                ('detail', models.CharField(default=b'', max_length=300, blank=True)),
                ('attach', models.CharField(default=b'', max_length=150, blank=True)),
                ('transaction_id', models.CharField(default=b'', max_length=100)),
                ('total_fee', models.IntegerField()),
                ('spbill_create_ip', models.CharField(default=b'', max_length=30)),
                ('start_time', models.DateTimeField()),
                ('time_expire', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True, blank=True)),
                ('trade_type', models.CharField(default=b'NATIVE', max_length=10)),
                ('limit_pay', models.CharField(default=b'no_credit', max_length=10, blank=True)),
                ('openid', models.CharField(default=b'', max_length=10, blank=True)),
                ('is_order_over', models.BooleanField(default=False)),
                ('order_status', models.SmallIntegerField(default=0, choices=[(0, '\u8fdb\u884c\u4e2d'), (1, '\u652f\u4ed8\u5931\u8d25'), (2, '\u9884\u652f\u4ed8\u4e2d'), (3, '\u652f\u4ed8\u6210\u529f'), (4, '\u672a\u652f\u4ed8'), (5, '\u5df2\u5173\u95ed'), (6, '\u5df2\u64a4\u9500'), (7, '\u7528\u6237\u652f\u4ed8\u4e2d'), (8, '\u8f6c\u5165\u9000\u6b3e'), (9, '\u7edf\u4e00\u4e0b\u5355\u5931\u8d25')])),
                ('order_status_desc', models.CharField(default=b'', max_length=200)),
                ('original_source', models.SmallIntegerField(choices=[(b'0', b'\xe7\xbd\x91\xe9\xa1\xb5\xe6\x89\xab\xe7\xa0\x81\xe6\x94\xaf\xe4\xbb\x98'), (b'1', b'android'), (b'2', b'ios')])),
                ('appid', models.CharField(max_length=32)),
                ('mch_id', models.CharField(max_length=32)),
                ('wx_return_code', models.CharField(default=b'', max_length=16, null=True, blank=True)),
                ('wx_return_msg', models.CharField(default=b'', max_length=200, null=True, blank=True)),
                ('wx_result_code', models.CharField(default=b'', max_length=16, null=True, blank=True)),
                ('wx_err_code', models.CharField(default=b'', max_length=100, null=True, blank=True)),
                ('wx_err_code_des', models.CharField(default=b'', max_length=200, null=True, blank=True)),
                ('wx_prepay_id', models.CharField(default=b'', max_length=70, null=True, blank=True)),
                ('code_url', models.CharField(default=b'', max_length=70, null=True, blank=True)),
                ('code_url_img_path', models.CharField(default=b'', max_length=300, null=True, blank=True)),
                ('code_url_img_url', models.CharField(default=b'', max_length=300, null=True, blank=True)),
                ('wx_response', models.CharField(default=b'', max_length=1000, null=True, blank=True)),
                ('comment', models.CharField(default=b'', max_length=600)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='abrechargewithdrawlog',
            old_name='comment',
            new_name='broker',
        ),
        migrations.RenameField(
            model_name='abrescindcontractlog',
            old_name='comment',
            new_name='user_comment',
        ),
        migrations.AddField(
            model_name='abrechargewithdrawhistory',
            name='cash_ex_code',
            field=models.CharField(default=b'2', max_length=10),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='cash_ex_code',
            field=models.CharField(default=b'2', max_length=10),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='enable_bala',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='host_serial',
            field=models.CharField(default=b'', max_length=60, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='inst_ratifier',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='money_usage',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='money_usage_info',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='summary',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='sys_comment',
            field=models.CharField(default=b'', max_length=2000, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='taster',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='trade_date',
            field=models.DateField(verbose_name='\u4ea4\u6613\u65e5\u671f', null=True, editable=False, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='trade_time',
            field=models.TimeField(verbose_name='\u4ea4\u6613\u65f6\u95f4', null=True, editable=False, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawlog',
            name='user_comment',
            field=models.CharField(default=b'', max_length=200, blank=True),
        ),
        migrations.AddField(
            model_name='abrescindcontractlog',
            name='sys_comment',
            field=models.CharField(default=b'', max_length=2000, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='address',
            field=models.CharField(default=b'', max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_address',
            field=models.CharField(default=b'', max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_email',
            field=models.CharField(default=b'', max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_fax_no',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_gender',
            field=models.CharField(default=b'', max_length=4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_mobile',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_nationality',
            field=models.CharField(default=b'', max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_postcode',
            field=models.CharField(default=b'', max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='agent_tel_no',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='email',
            field=models.CharField(default=b'', max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='fax_no',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='gender',
            field=models.CharField(default=b'', max_length=4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='mobile',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='nationality',
            field=models.CharField(default=b'', max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='absignincontractlog',
            name='postcode',
            field=models.CharField(default=b'', max_length=20, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='abrechargewithdrawlog',
            name='inst_serial',
            field=models.CharField(default=b'', unique=True, max_length=60, blank=True),
        ),
        migrations.AlterField(
            model_name='abrechargewithdrawlog',
            name='transfer_amount',
            field=models.DecimalField(max_digits=30, decimal_places=5),
        ),
        migrations.AlterField(
            model_name='abrescindcontractlog',
            name='inst_serial',
            field=models.CharField(default=b'', unique=True, max_length=60, blank=True),
        ),
        migrations.AlterField(
            model_name='abrescindcontractlog',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25'), (3, '\u672a\u63d0\u4ea4'), (4, '\u5904\u7406\u4e2d')]),
        ),
        migrations.AlterField(
            model_name='abrescindcontractlog',
            name='summary',
            field=models.CharField(default=b'', max_length=1000, blank=True),
        ),
        migrations.AlterField(
            model_name='absignincontractlog',
            name='inst_serial',
            field=models.CharField(default=b'', unique=True, max_length=60, blank=True),
        ),
        migrations.AlterField(
            model_name='absignincontractlog',
            name='summary',
            field=models.CharField(default=b'', max_length=1000, blank=True),
        ),
        migrations.AlterField(
            model_name='absignincontractlog',
            name='sys_comment',
            field=models.CharField(default=b'', max_length=2000, blank=True),
        ),
        migrations.AlterField(
            model_name='absignincontractlog',
            name='tel_no',
            field=models.CharField(default=b'', max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='abrechargewithdrawerrorstatus',
            name='market_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, blank=True, to='finance.AbRechargeWithdrawLog', null=True),
        ),
    ]
